"""Create initial tables for characters and relationships

Revision ID: 26736b56dc21
Revises: 
Create Date: 2025-09-01 16:33:48.191478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26736b56dc21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('occupation', sa.String(length=255), nullable=True),
    sa.Column('height_cm', sa.Integer(), nullable=True),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'NON_BINARY', 'OTHER', name='gender'), nullable=True),
    sa.Column('build', sa.Enum('SLIM', 'ATHLETIC', 'AVERAGE', 'MUSCULAR', 'HEAVYSET', name='buildtype'), nullable=True),
    sa.Column('race', sa.Enum('HUMAN', 'ELF', 'DWARF', 'ORC', 'GOBLIN', 'DRAGON', 'ANDROID', 'OTHER', name='race'), nullable=True),
    sa.Column('alignment', sa.Enum('LAWFUL_GOOD', 'NEUTRAL_GOOD', 'CHAOTIC_GOOD', 'LAWFUL_NEUTRAL', 'TRUE_NEUTRAL', 'CHAOTIC_NEUTRAL', 'LAWFUL_EVIL', 'NEUTRAL_EVIL', 'CHAOTIC_EVIL', name='alignment'), nullable=True),
    sa.Column('status', sa.Enum('ALIVE', 'DECEASED', 'MISSING_IN_ACTION', 'UNKNOWN', name='status'), nullable=True),
    sa.Column('measurements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('appearance_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('personality_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('background_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('speech_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_table('character_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_from_id', sa.UUID(), nullable=False),
    sa.Column('character_to_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('FAMILY', 'FRIEND', 'RIVAL', 'LOVER', 'ENEMY', 'MENTOR', 'SUBORDINATE', name='relationshiptype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['character_from_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['character_to_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_character_relationships_id'), 'character_relationships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_character_relationships_id'), table_name='character_relationships')
    op.drop_table('character_relationships')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
