"""add_bloodline_to_character

Revision ID: c720faa88660
Revises: 26736b56dc21
Create Date: 2025-09-04 09:22:16.228394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c720faa88660'
down_revision: Union[str, Sequence[str], None] = '26736b56dc21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先创建枚举类型
    bloodline_enum = sa.Enum('ROYAL', 'NOBLE', 'COMMON', 'ANCIENT', 'DIVINE', 'CURSED', 'MIXED', 'UNKNOWN', name='bloodline')
    bloodline_enum.create(op.get_bind())
    
    # 然后添加列
    op.add_column('characters', sa.Column('bloodline', bloodline_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删除列
    op.drop_column('characters', 'bloodline')
    
    # 然后删除枚举类型
    sa.Enum(name='bloodline').drop(op.get_bind())
    # ### end Alembic commands ###
